-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-27 21:14:56 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

SET ECHO ON
SPOOL wc_schema_output.txt

/*
Assignment 1B Group 41
Authors: Kang Hong Bo, Jeremy Yoon Zhe Min, Wang Qian
*/

DROP TABLE availability_range CASCADE CONSTRAINTS;

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE cruise CASCADE CONSTRAINTS;

DROP TABLE cruise_port CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE passenger_cruise CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE port_temperature CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

DROP TABLE tour_availability_range CASCADE CONSTRAINTS;

DROP TABLE tour_instance CASCADE CONSTRAINTS;

DROP TABLE tour_instance_passenger CASCADE CONSTRAINTS;

DROP TABLE tour_language CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE address (
    add_id       NUMBER(5) NOT NULL,
    add_street   VARCHAR2(35 CHAR) NOT NULL,
    add_town     VARCHAR2(35 CHAR) NOT NULL,
    add_postcode NUMBER(5) NOT NULL,
    add_country  VARCHAR2(60 CHAR) NOT NULL
);

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( add_id );


/*  ERROR: UK name length exceeds maximum allowed length(30) */
ALTER TABLE address
    ADD CONSTRAINT address_add_street_add_town_add_country_add_postcode_un UNIQUE ( add_street,
                                                                                  add_town,
                                                                                  add_country,
                                                                                  add_postcode );

CREATE TABLE availability_range (
    avail_range_desciptor VARCHAR2(10 CHAR) NOT NULL
);

ALTER TABLE availability_range
    ADD CONSTRAINT chk_tourrange CHECK ( avail_range_desciptor IN ( 'Daily', 'Fridays',
    'Mondays', 'Saturdays', 'Sundays',
                                                                    'Thursdays', 'Tuesdays',
                                                                    'Wednesdays', 'Weekdays',
                                                                    'Weekends' ) );

COMMENT ON COLUMN availability_range.avail_range_desciptor IS
    'Range of availability in tour';

ALTER TABLE availability_range ADD CONSTRAINT availability_range_pk PRIMARY KEY ( avail_range_desciptor );

CREATE TABLE cabin (
    cabin_number   NUMBER(3) NOT NULL,
    cabin_capacity NUMBER(2) NOT NULL,
    cabin_class    VARCHAR2(10 CHAR) NOT NULL,
    ship_code      CHAR(5 CHAR) NOT NULL
);

ALTER TABLE cabin
    ADD CHECK ( cabin_class IN ( 'Balcony', 'Interior', 'Ocean View', 'Suite' ) );

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cabin_number,
                                                        ship_code );

CREATE TABLE country (
    country_code CHAR(2 CHAR) NOT NULL,
    country_name VARCHAR2(60 CHAR) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_code );

CREATE TABLE cruise (
    cruise_id   NUMBER(4) NOT NULL,
    cruise_name VARCHAR2(50 CHAR) NOT NULL,
    cruise_desc VARCHAR2(80 CHAR) NOT NULL,
    ship_code   CHAR(5 CHAR) NOT NULL
);

ALTER TABLE cruise ADD CONSTRAINT cruise_pk PRIMARY KEY ( cruise_id );

CREATE TABLE cruise_port (
    cruise_port_date_tiime DATE NOT NULL,
    cruise_port_type       CHAR(1 CHAR) NOT NULL,
    port_code              CHAR(5 CHAR) NOT NULL,
    cruise_id              NUMBER(4) NOT NULL
);

ALTER TABLE cruise_port
    ADD CHECK ( cruise_port_type IN ( 'A', 'D' ) );

COMMENT ON COLUMN cruise_port.port_code IS
    'Port code';

ALTER TABLE cruise_port ADD CONSTRAINT cruise_port_pk PRIMARY KEY ( port_code,
                                                                    cruise_id );

CREATE TABLE language (
    lang_code CHAR(2 CHAR) NOT NULL,
    lang_name VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( lang_code );

CREATE TABLE operator (
    op_id       CHAR(5 CHAR) NOT NULL,
    op_com_name VARCHAR2(60 CHAR) NOT NULL,
    op_ceo_name VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( op_id );

CREATE TABLE passenger (
    pass_id          NUMBER(5) NOT NULL,
    pass_fname       VARCHAR2(50 CHAR) NOT NULL,
    pass_lname       VARCHAR2(50 CHAR) NOT NULL,
    pass_gender      CHAR(1 CHAR) NOT NULL,
    pass_dob         DATE NOT NULL,
    pass_phonenum    CHAR(15 CHAR),
    add_id           NUMBER(5) NOT NULL,
    lang_code        CHAR(2 CHAR) NOT NULL,
    pass_guardian_id NUMBER(5)
);

ALTER TABLE passenger
    ADD CHECK ( pass_gender IN ( 'F', 'M', 'O' ) );

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( pass_id );

CREATE TABLE passenger_cruise (
    pass_cruise_boarding_date_time DATE NOT NULL,
    cabin_number                   NUMBER(3) NOT NULL,
    pass_id                        NUMBER(5) NOT NULL,
    cruise_id                      NUMBER(4) NOT NULL,
    ship_code                      CHAR(5 CHAR) NOT NULL
);

ALTER TABLE passenger_cruise ADD CONSTRAINT passenger_cruise_pk PRIMARY KEY ( pass_id,
                                                                              cruise_id );

CREATE TABLE port (
    port_code       CHAR(5 CHAR) NOT NULL,
    port_name       VARCHAR2(20 CHAR) NOT NULL,
    port_population NUMBER(5) NOT NULL,
    port_longtitude NUMBER(10, 7) NOT NULL,
    port_latitude   NUMBER(10, 7) NOT NULL,
    country_code    CHAR(2 CHAR) NOT NULL
);

COMMENT ON COLUMN port.port_code IS
    'Port code';

COMMENT ON COLUMN port.port_name IS
    'Port name';

COMMENT ON COLUMN port.port_population IS
    'Port population';

COMMENT ON COLUMN port.port_longtitude IS
    'Port longtitude';

COMMENT ON COLUMN port.port_latitude IS
    'Port latitude';

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_code );

CREATE TABLE port_temperature (
    porttemp_month   VARCHAR2(4 CHAR) NOT NULL,
    porttemp_avghigh NUMBER(2) NOT NULL,
    porttemp_avglow  NUMBER(2) NOT NULL,
    port_code        CHAR(5 CHAR) NOT NULL
);

ALTER TABLE port_temperature
    ADD CHECK ( porttemp_month IN ( 'Apr', 'Aug', 'Dec', 'Feb', 'Jan',
                                    'July', 'Jun', 'Mar', 'May', 'Nov',
                                    'Oct', 'Sep' ) );

COMMENT ON COLUMN port_temperature.port_code IS
    'Port code';

ALTER TABLE port_temperature ADD CONSTRAINT port_temperature_pk PRIMARY KEY ( porttemp_month,
                                                                              port_code );

CREATE TABLE ship (
    ship_code            CHAR(5 CHAR) NOT NULL,
    ship_name            VARCHAR2(30 CHAR) NOT NULL,
    ship_commission_date DATE NOT NULL,
    ship_max_capacity    NUMBER(3) NOT NULL,
    ship_tonnage         NUMBER(3) NOT NULL,
    ship_country_name    CHAR(60) NOT NULL,
    op_id                CHAR(5 CHAR) NOT NULL
);

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_code );

CREATE TABLE tour (
    tour_num        NUMBER(3) NOT NULL,
    tour_name       VARCHAR2(20 CHAR) NOT NULL,
    tour_desc       VARCHAR2(100 CHAR) NOT NULL,
    tour_hrsreq     NUMBER(3, 2) NOT NULL,
    tour_cost       NUMBER(3) NOT NULL,
    tour_wheelchair VARCHAR2(3 CHAR) NOT NULL,
    tour_starttime  DATE NOT NULL,
    port_code       CHAR(5 CHAR) NOT NULL
);

ALTER TABLE tour
    ADD CHECK ( tour_wheelchair IN ( 'No', 'Yes' ) );

COMMENT ON COLUMN tour.tour_num IS
    'Tour number';

COMMENT ON COLUMN tour.tour_name IS
    'Tour name';

COMMENT ON COLUMN tour.port_code IS
    'Port code';

ALTER TABLE tour ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_num,
                                                      port_code );

CREATE TABLE tour_availability_range (
    tour_num              NUMBER(3) NOT NULL,
    port_code             CHAR(5 CHAR) NOT NULL,
    avail_range_desciptor VARCHAR2(10 CHAR) NOT NULL
);

COMMENT ON COLUMN tour_availability_range.tour_num IS
    'Tour number';

COMMENT ON COLUMN tour_availability_range.port_code IS
    'Port code';

COMMENT ON COLUMN tour_availability_range.avail_range_desciptor IS
    'Range of availability in tour';

ALTER TABLE tour_availability_range
    ADD CONSTRAINT tour_availability_range_pk PRIMARY KEY ( tour_num,
                                                            port_code,
                                                            avail_range_desciptor );

CREATE TABLE tour_instance (
    tour_date DATE NOT NULL,
    tour_num  NUMBER(3) NOT NULL,
    port_code CHAR(5 CHAR) NOT NULL
);

COMMENT ON COLUMN tour_instance.tour_num IS
    'Tour number';

COMMENT ON COLUMN tour_instance.port_code IS
    'Port code';

ALTER TABLE tour_instance
    ADD CONSTRAINT tour_instance_pk PRIMARY KEY ( tour_date,
                                                  tour_num,
                                                  port_code );

CREATE TABLE tour_instance_passenger (
    payment_received VARCHAR2(3 CHAR) NOT NULL,
    tour_date        DATE NOT NULL,
    tour_num         NUMBER(3) NOT NULL,
    port_code        CHAR(5 CHAR) NOT NULL,
    pass_id          NUMBER(5) NOT NULL
);

ALTER TABLE tour_instance_passenger
    ADD CHECK ( payment_received IN ( 'No', 'Yes' ) );

COMMENT ON COLUMN tour_instance_passenger.tour_num IS
    'Tour number';

COMMENT ON COLUMN tour_instance_passenger.port_code IS
    'Port code';

ALTER TABLE tour_instance_passenger
    ADD CONSTRAINT tour_instance_passenger_pk PRIMARY KEY ( tour_date,
                                                            tour_num,
                                                            port_code,
                                                            pass_id );

CREATE TABLE tour_language (
    lang_code CHAR(2 CHAR) NOT NULL,
    tour_num  NUMBER(3) NOT NULL,
    port_code CHAR(5 CHAR) NOT NULL
);

COMMENT ON COLUMN tour_language.tour_num IS
    'Tour number';

COMMENT ON COLUMN tour_language.port_code IS
    'Port code';

ALTER TABLE tour_language
    ADD CONSTRAINT tour_language_pk PRIMARY KEY ( tour_num,
                                                  port_code,
                                                  lang_code );

ALTER TABLE cabin
    ADD CONSTRAINT cabin_ship_fk FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_port_cruise_fk FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_port_port_fk FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE cruise
    ADD CONSTRAINT cruise_ship_fk FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE passenger
    ADD CONSTRAINT passenger_address_fk FOREIGN KEY ( add_id )
        REFERENCES address ( add_id );

ALTER TABLE passenger_cruise
    ADD CONSTRAINT passenger_cruise_cabin_fk FOREIGN KEY ( cabin_number,
                                                           ship_code )
        REFERENCES cabin ( cabin_number,
                           ship_code );

ALTER TABLE passenger_cruise
    ADD CONSTRAINT passenger_cruise_cruise_fk FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE passenger_cruise
    ADD CONSTRAINT passenger_cruise_passenger_fk FOREIGN KEY ( pass_id )
        REFERENCES passenger ( pass_id );

ALTER TABLE passenger
    ADD CONSTRAINT passenger_language_fk FOREIGN KEY ( lang_code )
        REFERENCES language ( lang_code );

ALTER TABLE passenger
    ADD CONSTRAINT passenger_passenger_fkv2 FOREIGN KEY ( pass_guardian_id )
        REFERENCES passenger ( pass_id );

ALTER TABLE port
    ADD CONSTRAINT port_country_fk FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE port_temperature
    ADD CONSTRAINT port_temperature_port_fk FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE ship
    ADD CONSTRAINT ship_operator_fk FOREIGN KEY ( op_id )
        REFERENCES operator ( op_id );

/*  ERROR: FK name length exceeds maximum allowed length(30) */
ALTER TABLE tour_availability_range
    ADD CONSTRAINT tour_availability_range_availability_range_fk FOREIGN KEY ( avail_range_desciptor )
        REFERENCES availability_range ( avail_range_desciptor );

/*  ERROR: FK name length exceeds maximum allowed length(30) */
ALTER TABLE tour_availability_range
    ADD CONSTRAINT tour_availability_range_tour_fk FOREIGN KEY ( tour_num,
                                                                 port_code )
        REFERENCES tour ( tour_num,
                          port_code );

/*  ERROR: FK name length exceeds maximum allowed length(30) */
ALTER TABLE tour_instance_passenger
    ADD CONSTRAINT tour_instance_passenger_passenger_fk FOREIGN KEY ( pass_id )
        REFERENCES passenger ( pass_id );

/*  ERROR: FK name length exceeds maximum allowed length(30) */
ALTER TABLE tour_instance_passenger
    ADD CONSTRAINT tour_instance_passenger_tour_instance_fk FOREIGN KEY ( tour_date,
                                                                          tour_num,
                                                                          port_code )
        REFERENCES tour_instance ( tour_date,
                                   tour_num,
                                   port_code );

ALTER TABLE tour_instance
    ADD CONSTRAINT tour_instance_tour_fk FOREIGN KEY ( tour_num,
                                                       port_code )
        REFERENCES tour ( tour_num,
                          port_code );

ALTER TABLE tour_language
    ADD CONSTRAINT tour_language_language_fk FOREIGN KEY ( lang_code )
        REFERENCES language ( lang_code );

ALTER TABLE tour_language
    ADD CONSTRAINT tour_language_tour_fk FOREIGN KEY ( tour_num,
                                                       port_code )
        REFERENCES tour ( tour_num,
                          port_code );

ALTER TABLE tour
    ADD CONSTRAINT tour_port_fk FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

SPOOL OFF
SET ECHO OFF

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                             0
-- ALTER TABLE                             47
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   5
-- WARNINGS                                 0
